import type { Chapter } from "../types.js";

const MDN_BASE = "https://developer.mozilla.org/ja/docs/Web/JavaScript";

export const chapters: Chapter[] = [
  {
    id: "Ch00",
    order: 0,
    label: "Ch00. セットアップ",
    description: "実行環境、console.log、エラー確認など最初の操作。",
    defaultMdnPage: `${MDN_BASE}/Guide/Introduction`,
  },
  {
    id: "Ch01",
    order: 1,
    label: "Ch01. 変数",
    description: "let / const、代入、命名、値の保持。",
    defaultMdnPage: `${MDN_BASE}/Guide/Grammar_and_types#宣言`,
  },
  {
    id: "Ch02",
    order: 2,
    label: "Ch02. 数値・演算",
    description: "数値リテラル、算術演算子、演算子の優先順位、Math。",
    defaultMdnPage: `${MDN_BASE}/Guide/Expressions_and_operators`,
  },
  {
    id: "Ch03",
    order: 3,
    label: "Ch03. 文字列",
    description: "文字列リテラル、連結、テンプレート、基本メソッド。",
    defaultMdnPage: `${MDN_BASE}/Guide/Text_formatting`,
  },
  {
    id: "Ch04",
    order: 4,
    label: "Ch04. 配列",
    description: "配列の作成、参照、更新、基本メソッド。",
    defaultMdnPage: `${MDN_BASE}/Guide/Indexed_collections`,
  },
  {
    id: "Ch05",
    order: 5,
    label: "Ch05. 条件分岐",
    description: "if / else、比較、論理演算、switch。",
    defaultMdnPage: `${MDN_BASE}/Guide/Control_flow_and_error_handling`,
  },
  {
    id: "Ch06",
    order: 6,
    label: "Ch06. ループ",
    description: "for / while / for...of と break / continue。",
    defaultMdnPage: `${MDN_BASE}/Guide/Loops_and_iteration`,
  },
  {
    id: "Ch07",
    order: 7,
    label: "Ch07. 関数",
    description: "関数宣言、引数、return、スコープの入り口。",
    defaultMdnPage: `${MDN_BASE}/Guide/Functions`,
  },
  {
    id: "Ch08",
    order: 8,
    label: "Ch08. オブジェクト",
    description: "プロパティ、メソッド、Object 操作、不変更新。",
    defaultMdnPage: `${MDN_BASE}/Guide/Working_with_objects`,
  },
  {
    id: "Ch09",
    order: 9,
    label: "Ch09. 高階関数",
    description: "コールバック、map / filter / reduce などの配列処理。",
    defaultMdnPage: `${MDN_BASE}/Reference/Global_Objects/Array`,
  },
  {
    id: "Ch10",
    order: 10,
    label: "Ch10. データ構造",
    description: "Map / Set、集計、探索に使うデータの持ち方。",
    defaultMdnPage: `${MDN_BASE}/Guide/Keyed_collections`,
  },
  {
    id: "Ch11",
    order: 11,
    label: "Ch11. アルゴリズム",
    description: "探索、ソート、累積、二重ループなどの考え方。",
    defaultMdnPage: `${MDN_BASE}/Guide/Loops_and_iteration`,
  },
  {
    id: "Ch12",
    order: 12,
    label: "Ch12. デバッグ",
    description: "console.log、エラーの読み方、切り分け、検証。",
    defaultMdnPage: `${MDN_BASE}/Guide/Control_flow_and_error_handling`,
  },
  {
    id: "Ch13",
    order: 13,
    label: "Ch13. エラー処理",
    description: "try / catch、throw、Error オブジェクト。",
    defaultMdnPage: `${MDN_BASE}/Guide/Control_flow_and_error_handling#例外処理文`,
  },
  {
    id: "Ch14",
    order: 14,
    label: "Ch14. 正規表現",
    description: "RegExp、match / replace、キャプチャ。",
    defaultMdnPage: `${MDN_BASE}/Guide/Regular_expressions`,
  },
  {
    id: "Ch15",
    order: 15,
    label: "Ch15. class",
    description: "class、constructor、メソッド、継承、private。",
    defaultMdnPage: `${MDN_BASE}/Guide/Using_classes`,
  },
  {
    id: "Ch16",
    order: 16,
    label: "Ch16. 非同期",
    description: "Promise、async / await、非同期処理の合成。",
    defaultMdnPage: `${MDN_BASE}/Guide/Using_promises`,
  },
];
